### ISSUE TITLE
unhandled fetching/streaming error

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [RhysSullivan/shiptalkers#33]
![image](https://github.com/RhysSullivan/shiptalkers/assets/65041082/d0c6017b-d71d-48f5-9c45-f602b934935f)
been an hour this way, neither errors shown nor streamed data
![image](https://github.com/RhysSullivan/shiptalkers/assets/65041082/c05d3b0e-61e7-4fe3-8ed3-c8e23d6e01c3)

**Comment by RhysSullivan** [comment]
probably fixed by the million changes that i made, your page is loading correctly now https://shiptalkers.dev/compare?github=ebrahim-ramadan&twitter=scoopsahoykid
