### ISSUE TITLE
my account is still stuck 

### ISSUE THREAD

**Issue by ImLunaHey** [RhysSullivan/shiptalkers#35]
been stuck at 8k tweets for a while now https://shiptalkers.dev/compare?name=imlunahey

**Comment by loftwah** [comment]
Mine too: https://shiptalkers.dev/compare?name=loftwah

**Comment by RhysSullivan** [comment]
resolved the one with @ImLunaHey  - @loftwah i've also set yours up to refetch and it looks like it's loading now
