### ISSUE TITLE
users who are updating arent included on the homepage

### ISSUE THREAD

**Issue by ImLunaHey** [RhysSullivan/shiptalkers#40]
everytime the update kicks in im pulled from the homepage 👀

**Comment by RhysSullivan** [comment]
this one is because i've manually wiped you from the database and we need the sync to complete for you to be written back - once if finishes you should appear

**Comment by ImLunaHey** [comment]
oh lol this is gonna be a while then. ive got 27k tweets.

<img width="193" alt="Screenshot 2024-06-06 at 5 47 27 PM" src="https://github.com/RhysSullivan/shiptalkers/assets/105922175/91b66e6c-1dc3-4446-b2c9-778a63106459">
