### ISSUE TITLE
Private commits

### ISSUE THREAD

**Issue by brandonmcconnell** [RhysSullivan/shiptalkers#45]
It would be great if the app supported a low-level GitHub integration, so it could include counts for private commits.

**Comment by styfle** [comment]
I already have that box checked but it doesn't seem to work.

GitHub shows 2768:

<img width="764" alt="image" src="https://github.com/RhysSullivan/shiptalkers/assets/229881/e636ebfb-c7dc-4f72-9fa4-ab3d2730fbbb">

Shiptalkers shows 1271

<img width="573" alt="image" src="https://github.com/RhysSullivan/shiptalkers/assets/229881/9deec89f-bf0f-49aa-a0b0-5113fc0e6201">

**Comment by RhysSullivan** [comment]
should be fixed with the introduciton of the reload button https://shiptalkers.dev/compare?name=styfle
