### ISSUE TITLE
sorry for yet another issue lol...

### ISSUE THREAD

**Issue by nandorojo** [RhysSullivan/shiptalkers#48]
@FernandoTheRojo on Twitter appears to not load.

**Comment by RhysSullivan** [comment]
Works on my machine:

https://shiptalkers.dev/compare?github=nandorojo&twitter=fernandotherojo

**Comment by RhysSullivan** [comment]
![image](https://github.com/RhysSullivan/shiptalkers/assets/39114868/6c6c6c39-0194-425d-885a-d92fdc423926)

**Comment by nandorojo** [comment]
works now! thanks!
