### ISSUE TITLE
Twitter name and GitHub profile not exactly the same causes fail

### ISSUE THREAD

**Issue by packetrat** [RhysSullivan/shiptalkers#53]
For example, my GitHub profile is packetrat and my Twitter handle is thepacketrat because packetrat was taken. Data is returned for my GitHub but connected with a non-coder who owns the matching account name, not pulling Twitter name from my GitHub profile.

**Comment by hahn** [comment]
you can use this url https://shiptalkers.dev/compare?github=packetrat &twitter=thepacketrat

**Comment by RhysSullivan** [comment]
going to assume the reload button fixes this, reopen with your url if it doesnt
