### ISSUE TITLE
Mine GitHub doesn't load

### ISSUE THREAD

**Issue by KevinZonda** [RhysSullivan/shiptalkers#58]
<img width="618" alt="image" src="https://github.com/RhysSullivan/shiptalkers/assets/33132228/8cfbc784-e5c2-4912-821a-b4dcea6df015">

lol

**Comment by StanleyMasinde** [comment]
Haha same. I’m a Twitter addict but not this much 😭😂

**Comment by jkudish** [comment]
I had the same issue, but finally got it to work by clicking reload: 
![image](https://github.com/RhysSullivan/shiptalkers/assets/260253/fac2d694-a64f-44b3-9b30-5b65df878c7a)

**Comment by RhysSullivan** [comment]
going to assume the reload button fixes all these, open a new issue with your url if it doesnt
