### ISSUE TITLE
if your github username and twitter username is the game, Github stats do not load

### ISSUE THREAD

**Issue by barrymcgee** [RhysSullivan/shiptalkers#60]
Example: https://shiptalkers.dev/compare?name=barrymcgee

**Comment by adsalihac** [comment]
yes , both are same , it is not working

**Comment by RhysSullivan** [comment]
Working now, please verify and reopen if it isn't

**Comment by hrittikhere** [comment]
It doesn't yet. Just tried
![Uploading image.png…]()
