### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by tarngerine** [RhysSullivan/shiptalkers#61]
some way to bust cache/refresh would be nice. i didnt realize i could enable private contribs to show up in my contrib graph so i toggled that on, wanted to see if that effected the graph. or maybe shiptalkers cant get those even if i toggled this setting on? not sure

<img width="989" alt="image" src="https://github.com/RhysSullivan/shiptalkers/assets/1629901/929665c7-1974-4e47-865d-2c22a859d65b">

**Comment by RhysSullivan** [comment]
added a refresh button, lmk if it works
