### ISSUE TITLE
Copy Image button not working

### ISSUE THREAD

**Issue by iqfareez** [RhysSullivan/shiptalkers#65]
![Screenshot 2024-06-07 at 9 17 17 AM](https://github.com/RhysSullivan/shiptalkers/assets/60868965/5f98a301-8276-4792-accd-d5c81948b665)

The button is not copying the image or anything.

Workaround:

Right click and copy the image

![Screenshot 2024-06-07 at 9 18 41 AM](https://github.com/RhysSullivan/shiptalkers/assets/60868965/c477a01a-8602-4ace-8959-48e1619efece)

**Comment by maxdemaio** [comment]
Are there any errors in the console at all when you try this? I could take a look at why this wouldn't be working

**Comment by RhysSullivan** [comment]
i think the fix is to use chrome

**Comment by RhysSullivan** [comment]
probably fixed by theo's PR, please reopen if still occuring
