### ISSUE TITLE
Improve Responsive Design by Using Icons Only for Social Buttons on Mobile Devices

### ISSUE THREAD

**Issue by paulbgtr** [RhysSullivan/shiptalkers#66]
Currently, the responsive design of the project is impacted by the text "Follow me on Twitter" and "Star on GitHub" along with their respective icons. These elements take up too much space on mobile devices, leading to a poor user experience.

To enhance the responsive design, I propose the following changes:

- On mobile devices, remove the text "Follow me on Twitter" and "Star on GitHub".
- Retain only the icons for Twitter and GitHub on mobile devices.

**Comment by RhysSullivan** [comment]
fixed via Retain only the icons for Twitter and GitHub on mobile devices.
