### ISSUE TITLE
Commit counts seem to be wrong

### ISSUE THREAD

**Issue by MikeMcQuaid** [RhysSullivan/shiptalkers#67]
This tool is a fun idea, nice work!

The commit counts don't seem quite right, though. From https://shiptalkers.dev/compare?name=mikemcquaid I apparently have ~4k commits but on Homebrew/brew it lists >10k: https://github.com/Homebrew/brew/graphs/contributors

Happy to help with any debugging information here if it'll help.

**Comment by RhysSullivan** [comment]
Gave it a refresh and it seems fixed, 63k commits is insane holy cow

Thank you for your work on brew 🍻

**Comment by MikeMcQuaid** [comment]
> 171865%

😎

Thanks for this tool and for the quick response here!

Just wish it could have my commits from 10 years at GitHub too 😅
